-- Migration: add media and interactive exercise fields to lessons table

ALTER TABLE lessons
  ADD COLUMN IF NOT EXISTS intro_video_url   TEXT,
  ADD COLUMN IF NOT EXISTS video_subtitles   JSONB   NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS exercises         JSONB   NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS ui_language       TEXT    NOT NULL DEFAULT 'es';

COMMENT ON COLUMN lessons.intro_video_url  IS 'Public URL of the intro video in Supabase Storage (lesson-media bucket)';
COMMENT ON COLUMN lessons.video_subtitles  IS 'JSON object: { "es": "url.vtt", "en": "url.vtt", "it": "url.vtt" }';
COMMENT ON COLUMN lessons.exercises        IS 'Array of Exercise objects generated by Gemini from the exercise guide';
COMMENT ON COLUMN lessons.ui_language      IS 'Language for instructions, exercises and exam: es | en | it';
